name: Continuous Integration

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PIPENV_VENV_IN_PROJECT: 1
  PIPENV_IGNORE_VIRTUALENVS: 1

jobs:
  HGF-JOB:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:13.5
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_DB: testdb
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
          
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.8

    - name: Copiando as configuraçõs
      run: |
        cp contrib/.env-sample .env

    - name: Instalar Dependências
      run: |
        pip install pipenv codecov
        pipenv sync --dev

    - name: Lint com flake8
      run: |
        pipenv run flake8 --max-line-length 190

    - name: Testes com PyTest e CodeCov
      run: |
        pipenv run pytest --cov=pypro
        pipenv run codecov
